# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataentry.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1600, 700)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(370, 20, 201, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.examList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.examList.setObjectName("examList")
        self.verticalLayout.addWidget(self.examList)
        self.returnToHome = QtWidgets.QPushButton(Form)
        self.returnToHome.setGeometry(QtCore.QRect(40, 630, 531, 41))
        self.returnToHome.setObjectName("returnToHome")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 321, 421))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.patientList = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.patientList.setObjectName("patientList")
        self.verticalLayout_2.addWidget(self.patientList)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.baselineExamSelect = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.baselineExamSelect.setObjectName("baselineExamSelect")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baselineExamSelect)
        self.setExams = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.setExams.setObjectName("setExams")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.setExams)
        self.currentExamSelect = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.currentExamSelect.setObjectName("currentExamSelect")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentExamSelect)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(40, 450, 531, 171))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 103, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(600, 19, 61, 21))
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(600, 50, 971, 621))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.tree_container = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.tree_container.setContentsMargins(0, 0, 0, 0)
        self.tree_container.setObjectName("tree_container")
        self.lineedit_patient_name = QtWidgets.QLineEdit(Form)
        self.lineedit_patient_name.setEnabled(False)
        self.lineedit_patient_name.setGeometry(QtCore.QRect(660, 20, 361, 22))
        self.lineedit_patient_name.setObjectName("lineedit_patient_name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Patient Data Overrides"))
        self.label.setText(_translate("Form", "Exams:"))
        self.returnToHome.setText(_translate("Form", "Finish"))
        self.label_4.setText(_translate("Form", "Patient Selection (highlight patient to modify):"))
        self.label_3.setText(_translate("Form", "Baseline Exam:"))
        self.setExams.setText(_translate("Form", "Set Exams"))
        self.label_2.setText(_translate("Form", "Current Exam:"))
        self.groupBox.setTitle(_translate("Form", "Additional Controls"))
        self.label_5.setText(_translate("Form", "Course:"))
        self.label_6.setText(_translate("Form", "Day:"))
        self.label_7.setText(_translate("Form", "Patient:"))

